### ISSUE TITLE
Drop in favor of markfink/nest2D (LGPL now!)

### ISSUE THREAD

**Issue by StefanBruens** [Ultimaker/pynest2d#15]
nest2d was changed to LGPL:
https://github.com/markfink/nest2D/commit/4e6605d519ff8aac26036589a5dbc89fc2bd0ae4

**Comment by Ghostkeeper** [comment]
That project seems to intend functionally the same as what this project intends to do, except that it is missing the functionality to mark off disallowed areas which is needed for Cura, and misses the configurability that Cura needs.

We can indeed update the readme in this repository though.
