### ISSUE TITLE
Overlapped polygons output

### ISSUE THREAD

**Issue by Hokyjack** [Ultimaker/pynest2d#18]
Hi, a have a set of 5 polygons, but when I run the algorithm, some of the polygons overlaps in the transformed shape.
I checked also by using rotation() and translation() on the original polygons, but the result is same and still incorrect.
Also tried to offset them to be in the positive coordinates - no change of the output...

Any toughts what could be wrong?  

Here is the list of the 5 polygons:
`[Item([Point(216,-31),Point(176,-31),Point(136,-31),Point(136,-10),Point(136,24),Point(120,24),Point(108,24),Point(108,62),Point(108,100),Point(48,100),Point(-3,100),Point(-41,100),Point(-79,100),Point(-79,56),Point(-79,54),Point(-80,54),Point(-81,54),Point(-81,39),Point(-81,24),Point(-81,24),Point(-109,24),Point(-109,-10),Point(-109,-31),Point(-151,-31),Point(-193,-31),Point(-193,-108),Point(-193,-185),Point(11,-185),Point(216,-185),Point(216,-108)]),Item([Point(80,87),Point(80,99),Point(0,99),Point(-80,99),Point(-80,87),Point(-80,75),Point(-83,75),Point(-128,75),Point(-128,43),Point(-128,41),Point(-156,41),Point(-184,41),Point(-184,-61),Point(-184,-164),Point(-172,-164),Point(-160,-164),Point(0,-164),Point(160,-164),Point(172,-164),Point(184,-164),Point(184,-61),Point(184,41),Point(156,41),Point(128,41),Point(128,43),Point(128,75),Point(83,75),Point(80,75)]),Item([Point(-56,94),Point(-56,87),Point(-59,87),Point(-64,87),Point(-64,79),Point(-64,73),Point(-65,73),Point(-66,73),Point(-66,70),Point(-66,67),Point(-68,67),Point(-76,67),Point(-76,-54),Point(-76,-176),Point(-45,-176),Point(-38,-176),Point(-38,-198),Point(-38,-220),Point(36,-220),Point(111,-220),Point(111,-209),Point(111,-198),Point(111,-195),Point(111,-176),Point(111,-62),Point(111,51),Point(111,122),Point(111,133),Point(111,145),Point(111,157),Point(36,157),Point(-38,157),Point(-38,129),Point(-38,101),Point(-46,101),Point(-56,101)]),Item([Point(-74,-112),Point(-74,-177),Point(-23,-177),Point(3,-177),Point(60,-177),Point(117,-177),Point(117,-69),Point(117,18),Point(117,62),Point(117,106),Point(64,106),Point(11,106),Point(11,93),Point(11,86),Point(8,86),Point(5,86),Point(-26,86),Point(-58,86),Point(-58,76),Point(-58,66),Point(-59,66),Point(-64,66),Point(-64,9),Point(-64,-47),Point(-69,-47),Point(-74,-47)]),Item([Point(-81,117),Point(-88,117),Point(-95,117),Point(-95,15),Point(-95,-86),Point(-95,-97),Point(-95,-126),Point(-72,-126),Point(-49,-126),Point(-7,-126),Point(20,-126),Point(20,-157),Point(20,-188),Point(50,-188),Point(80,-188),Point(80,-156),Point(80,-124),Point(80,-102),Point(80,-70),Point(80,53),Point(80,141),Point(80,163),Point(80,185),Point(50,185),Point(20,185),Point(20,163),Point(20,141),Point(-18,141),Point(-81,141),Point(-81,123)])]`

and the output from the pynest2d shows this packing:
![image](https://user-images.githubusercontent.com/8573741/171309594-0feaa16d-2cef-4c25-9e2c-ac0724f5b352.png)

**Comment by YazdanArman** [comment]
would you please send you code?

**Comment by Hokyjack** [comment]
the problem was that some polygons where not convex. As this lib cannot handle this type of polygons, it's not a bug, so I am closing the issue. Thank you!
