### ISSUE TITLE
Built on Linux, how to use in venv

### ISSUE THREAD

**Issue by mansman12** [Ultimaker/pynest2d#30]
Followed the building instructions, now am confused on how to import the module in to a project (or use in a venv).

From the cmake_install I can see the files go somewhere but 'conan build .' doesn't show where.

There are files in build\Release\site-packages which I assumed could just be copied over to the site-packages folder in the venv, that satisfies a pip show but still raises an import error.

**Comment by jellespijker** [comment]
the so file needs to be present in the site-packages or on the PYTHONPATH of your python env and if you build it with shared the dependencies libraries need to be on your PATH or LD_LIBRARY_PATH

**Comment by mansman12** [comment]
Okay, copying the 'pynest2d.so' in to the site-packages folder of the venv solves the import error and my code runs as normal.

Any issues with not copying across the contents of site-packages (i.e. pynest2d.pyi, pynest2d.cpython-...so, pynest2d-5.3.0a.dist-info)?

**Comment by jellespijker** [comment]
These aren't needed, but the pyi file might be handy if you want to use typing suggestions in your IDE
