### ISSUE TITLE
Tag release for libnest2d

### ISSUE THREAD

**Issue by karl-nilsson** [Ultimaker/pynest2d#5]
I'm attempting to package pynest2d, which depends on your fork of libnest2d.
Please tag a release for libnest2d
thanks!

**Comment by Ghostkeeper** [comment]
Libnest2d doesn't put its version numbering anywhere in its installation, so pynest2d cannot detect the version number of an installation and thus can't require any version number in its CMake find script.

We are kind of hoping that https://github.com/tamasmeszaros/libnest2d/pull/18 will be merged at some point which will make it easier for people to keep using the upstream version.

**Comment by karl-nilsson** [comment]
Wow, I didn't realize libnest2d doesn't provide any version info.
Thanks for the response!
