### ISSUE TITLE
SIP version

### ISSUE THREAD

**Issue by erathke** [Ultimaker/pynest2d#6]
Hi folks!
I'm updating my Cura building on OpenBSD 6.8 and with this new dependency (pynest2d) I'm getting compile errors:

[5/10] /usr/ports/pobj/pynest2d-4.8.0-python3/bin/c++  -Dpython_module_pynest2d_EXPORTS -I/usr/ports/pobj/pynest2d-4.8.0-python3/pynest2d-4.8.0/src -I/usr/local/include/python3.8 -I/usr/local/include/polyclipping -I/usr/local/include -O2 -pipe -DLIBNEST2D_GEOMETRIES_clipper -DLIBNEST2D_OPTIMIZERS_nlopt -DLIBNEST2D_THREADING_std -fPIC -DNDEBUG -fPIC   -std=gnu++11 -MD -MT CMakeFiles/python_module_pynest2d.dir/src/sippynest2dpart3.cpp.o -MF CMakeFiles/python_module_pynest2d.dir/src/sippynest2dpart3.cpp.o.d -o CMakeFiles/python_module_pynest2d.dir/src/sippynest2dpart3.cpp.o -c src/sippynest2dpart3.cpp
FAILED: CMakeFiles/python_module_pynest2d.dir/src/sippynest2dpart3.cpp.o 
/usr/ports/pobj/pynest2d-4.8.0-python3/bin/c++  -Dpython_module_pynest2d_EXPORTS -I/usr/ports/pobj/pynest2d-4.8.0-python3/pynest2d-4.8.0/src -I/usr/local/include/python3.8 -I/usr/local/include/polyclipping -I/usr/local/include -O2 -pipe -DLIBNEST2D_GEOMETRIES_clipper -DLIBNEST2D_OPTIMIZERS_nlopt -DLIBNEST2D_THREADING_std -fPIC -DNDEBUG -fPIC   -std=gnu++11 -MD -MT CMakeFiles/python_module_pynest2d.dir/src/sippynest2dpart3.cpp.o -MF CMakeFiles/python_module_pynest2d.dir/src/sippynest2dpart3.cpp.o.d -o CMakeFiles/python_module_pynest2d.dir/src/sippynest2dpart3.cpp.o -c src/sippynest2dpart3.cpp
/usr/ports/pobj/pynest2d-4.8.0-python3/pynest2d-4.8.0/src/ItemGroup.sip:49:25: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
        while(list_item = PyIter_Next(iterator))
              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/pobj/pynest2d-4.8.0-python3/pynest2d-4.8.0/src/ItemGroup.sip:49:25: note: place parentheses around the assignment to silence this warning
        while(list_item = PyIter_Next(iterator))
                        ^
              (                                )
/usr/ports/pobj/pynest2d-4.8.0-python3/pynest2d-4.8.0/src/ItemGroup.sip:49:25: note: use '==' to turn this assignment into an equality comparison
        while(list_item = PyIter_Next(iterator))
                        ^
                        ==
/usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3/src/sippynest2dpart3.cpp:283:30: error: no member named 'isDisallowedArea' in 'libnest2d::_Item<ClipperLib::Polygon>'
            sipRes = sipCpp->isDisallowedArea();
                     ~~~~~~  ^
/usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3/src/sippynest2dpart3.cpp:356:21: error: no member named 'markAsDisallowedAreaInBin' in 'libnest2d::_Item<ClipperLib::Polygon>'
            sipCpp->markAsDisallowedAreaInBin(a0);
            ~~~~~~  ^
1 warning and 2 errors generated.
ninja: build stopped: subcommand failed.
*** Error 1 in . (/usr/ports/devel/cmake/cmake.port.mk:36 'do-build': @cd /usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3 && exec...)
*** Error 2 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2921 '/usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3/.build_done': @c...)
*** Error 2 in /usr/ports/mystuff/cad/ultimaker/pynest2d (/usr/ports/infrastructure/mk/bsd.port.mk:2584 'build': @lock=pynest2d-4.8.0;  expo...)

I'm using SIP 4 version. 

Do you have some tips to solve it?

Thanks in advance.

Evandro Rathke

**Comment by Ghostkeeper** [comment]
> /usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3/src/sippynest2dpart3.cpp:283:30: error: no member named 'isDisallowedArea' in 'libnest2d::_ItemClipperLib::Polygon'
sipRes = sipCpp->isDisallowedArea();
~~~~~~ ^
/usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3/src/sippynest2dpart3.cpp:356:21: error: no member named 'markAsDisallowedAreaInBin' in 'libnest2d::_ItemClipperLib::Polygon'
sipCpp->markAsDisallowedAreaInBin(a0);

These two are the real error you're encountering and it's not anything to do with the SIP version but rather the libnest2d version.

When we developed those Python bindings for usage in Cura we also added a feature to libnest2d: Disallowed areas. This is something that Cura kind of needs in order to work properly. It has locations on the build plate where models are not allowed to be positioned, but models shouldn't be positioned next to those locations either (they should start aligned in the middle). We made a pull request to add this: https://github.com/tamasmeszaros/libnest2d/pull/18 However this pull request is not merged due to foreseen issues.

The solution, for now, is to use Ultimaker's version of libnest2d with the feature added, rather than the mainline version: https://github.com/Ultimaker/libnest2d/tree/CURA-7754_add_disallowed_areas

**Comment by erathke** [comment]
> ```
> /usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3/src/sippynest2dpart3.cpp:283:30: error: no member named 'isDisallowedArea' in 'libnest2d::_ItemClipperLib::Polygon'
> sipRes = sipCpp->isDisallowedArea();
> ~~~~~~ ^
> /usr/ports/pobj/pynest2d-4.8.0-python3/build-amd64-python3/src/sippynest2dpart3.cpp:356:21: error: no member named 'markAsDisallowedAreaInBin' in 'libnest2d::_ItemClipperLib::Polygon'
> sipCpp->markAsDisallowedAreaInBin(a0);
> ```
> 
> These two are the real errors you're encountering and it's not anything to do with the SIP version but rather the libnest2d version.
> 
> When we developed those Python bindings for usage in Cura we also added a feature to libnest2d: Disallowed areas. This is something that Cura kind of needs in order to work properly. It has locations on the build plate where models are not allowed to be positioned, but models shouldn't be positioned next to those locations either (they should start aligned in the middle). We made a pull request to add this: [tamasmeszaros/libnest2d#18](https://github.com/tamasmeszaros/libnest2d/pull/18) However this pull request is not merged due to foreseen issues.
> 
> The solution, for now, is to use Ultimaker's version of libnest2d with the feature added, rather than the mainline version: https://github.com/Ultimaker/libnest2d/tree/CURA-7754_add_disallowed_areas

It works! Thanks for your help!  
Have a good week!
